# Generated by Django 5.2.2 on 2025-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORD', 'Coordinador'), ('EVAL', 'Evaluador'), ('PRACT', 'Practicante')], default='PRACT', max_length=10),
        ),
    ]
