# Generated by Django 5.2.2 on 2025-06-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0002_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORD', 'Coordinador'), ('EVAL', 'Evaluador'), ('PRACT', 'Practicante'), ('EMPRESA', 'Empresa')], default='PRACT', max_length=10),
        ),
    ]
