# Generated by Django 5.2.2 on 2025-06-20 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0003_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('CERRADA', 'Cerrada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ASIGNADA', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos_practicas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_publicadas', to=settings.AUTH_USER_MODEL)),
                ('practicante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_practicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
