# Generated by Django 5.2.2 on 2025-06-21 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0004_practica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('CERRADA', 'Cerrada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('CERRADA', 'Cerrada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='practic.practica')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
