# Generated by Django 5.2.2 on 2025-07-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0005_historialestado_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORD', 'Coordinador'), ('EVAL', 'Evaluador'), ('PRACT', 'Practicante'), ('EMPRESA', 'Empresa')], default='PRACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
