# Generated by Django 5.2.2 on 2025-07-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0006_remove_perfil_curriculum_perfil_carrera_perfil_cv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PUBLICADA', 'Publicada'), ('POR_REVISAR', ' Por revisar '), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PUBLICADA', 'Publicada'), ('POR_REVISAR', ' Por revisar '), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PUBLICADA', 'Publicada'), ('POR_REVISAR', ' Por revisar '), ('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('TERMINADA', 'Terminada'), ('EVALUADA', 'Evaluada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ASIGNADA', max_length=20),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='practic.practica')),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('practicante', 'practica')},
            },
        ),
    ]
