# Generated by Django 5.2.2 on 2025-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0007_alter_historialestado_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='informe_evaluacion',
            field=models.FileField(blank=True, null=True, upload_to='informes/'),
        ),
    ]
