# Generated by Django 5.2.2 on 2025-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0008_practica_informe_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='aprobado_por_coordinador',
            field=models.BooleanField(default=False),
        ),
    ]
