# Generated by Django 5.2.2 on 2026-01-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic', '0009_postulacion_aprobado_por_coordinador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_evaluadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
